################################################################################
# Old results include: 
#
# Those in thetas_9MS and thetas_9MS_Tagnostic, which include mean and quantiles
# for all data modelled jointly using the time-to-event and uniform priors.
#
# Those in MS_final, which is generated by running the code chunks in
# RecurrentVivax/Pooled_Final_Analysis/Pooled_Analysis.Rmd. The results in
# MS_final include the 2.5, 0.5, 97.5 quantiles of the distributions generated
# by running the prototype 100 times, each time with a different draws from the
# time-to-event posterior and the posterior on allele frequencies. The results
# are generated using data modelled jointly or pairwise.
################################################################################
rm(list = ls())
library(Pv3Rs)
Figs <- TRUE
states <- c(Recrudescence = "C", Reinfection = "I", Relapse = "L")
par_default <- par()
big_diff <- 0.25
load("../RData/marg_results_Pv3Rs.RData") # Pv3R generated results
path <- "../jwatowatson-RecurrentVivax-4870715/" # Path to old estimates
load(sprintf('%sRData/GeneticModel/Including_Complex_Cases_Full_Posterior_Model_samples_Tagnostic.RData', path))
load(sprintf('%sRData/GeneticModel/Including_Complex_Cases_Full_Posterior_Model_samples.RData', path))
load("../Rdata/MS_final_generated_by_running_all_chunks_of_Pooled_Analysis.Rmd")
rownames(MS_final) <- MS_final[,"Episode_Identifier"]

# Global summary: 
summary(1-TimeToEvent_Pv3Rs[,"I"])
summary(1-MS_final[,"I_median"])
summary(1-thetas_9MS_Tagnostic[,"I50%"])
summary(1-Uniform_Pv3Rs[rownames(thetas_9MS_Tagnostic),"I"])


#===============================================================================
# Sanity check that median values are the same across MS_final and thetas_9MS
#===============================================================================
all(MS_final[rownames(thetas_9MS), "C"] == thetas_9MS[,"C50%"], na.rm = T)
all(MS_final[rownames(thetas_9MS), "L"] == thetas_9MS[,"L50%"], na.rm = T)
all(MS_final[rownames(thetas_9MS), "I"] == thetas_9MS[,"I50%"], na.rm = T)
# thetas_9MS inc pids with total MOI 6 where MS_final doesn't, hence na.rm = T 
# These three participants are included in thetas_9MS because inference was 
# attempted but failed; VHX_583, VHX_39, VHX_33 were not tried
rownames(thetas_9MS)[!rownames(thetas_9MS) %in% rownames(MS_final)] 

#===============================================================================
# Plot on the simplex 
#===============================================================================
# Source function, project probabilities, add joint indicator, plot
source("plot_VHXBPD_simplex.R") # Wrapper to avoid code duplication
if(Figs) png("../Figures/simplex_prototype.png",
             width = 9, height = 9, units = "in", res = 300)
na_log <- !is.na(thetas_9MS_Tagnostic$`C50%`) # Some entries have NA estimates
Uniform_xy <- apply(thetas_9MS_Tagnostic[na_log, c("C50%", "L50%", "I50%")], 1, project2D)
TimeToEvent_xy <- apply(MS_final[,c("C_median", "L_median", "I_median")], 1, project2D)
Uniform_xy <- rbind(Uniform_xy, joint = 1) # uniform prior not run for pids 4+ episodes
TimeToEvent_xy <- rbind(TimeToEvent_xy, joint = colnames(TimeToEvent_xy) %in% rownames(thetas_9MS))
plot_VHXBPD_simplex(Uniform_xy, TimeToEvent_xy)
if(Figs) dev.off()


#===============================================================================
# Compare median and mean old: mean estimates were generated for recurrences
# where data could be modelled jointly. Small variation between mean and median
# using the uniform prior suggests variation due to posterior allele-frequency
# draws (which we cannot exactly reproduce - we didn't use set.seed in
# Pooled_Analysis.Rmd) is inferior to variation due to to time-to-event draws
# (which we could reproduce but don't).
#===============================================================================
par(mfrow = c(2,3), mar = par_default$mar)
for(s in states){
  plot(x = thetas_9MS[, paste0(s,"50%")], y = thetas_9MS[,s], 
       xlab = "Prototype median", ylab = "Prototype mean", 
       xlim = c(0,1), ylim = c(0,1), pch = 20, bty = "n", 
       main = sprintf("%s: time-to-event prior", names(which(states == s))))
  abline(a = 0, b = 1, lty = "dotted")}

for(s in states){  
  plot(x = thetas_9MS_Tagnostic[, paste0(s,"50%")], y = thetas_9MS_Tagnostic[,s], 
       xlab = "Prototype median", ylab = "Prototype mean", 
       xlim = c(0,1), ylim = c(0,1), pch = 20, bty = "n", 
       main = sprintf("%s: uniform prior", names(which(states == s))))
  abline(a = 0, b = 1, lty = "dotted")}



#===============================================================================
# Compare Pv3Rs and prototype time-to-Event results: median for both jointly and
# pairwise modelled data; mean for jointly modelled data only
#===============================================================================

# Check overlap: 
all(rownames(MS_final) %in% rownames(TimeToEvent_Pv3Rs))
all(rownames(TimeToEvent_Pv3Rs) %in% rownames(MS_final))

# Check missing meets expectation: yes; see Analysable_data.png
rownames(TimeToEvent_Pv3Rs)[which(!rownames(TimeToEvent_Pv3Rs) %in% rownames(MS_final))]
# "VHX_239_2" "VHX_33_2"  "VHX_39_2"  "VHX_461_2" "VHX_52_2"  "VHX_583_2"

#===============================================================================
# Compare Pv3Rs and prototype uniform results: median and mean for joint only
# Unless it is decided to discuss mean estimates, avoid including them in ms plots
#===============================================================================
if(Figs) png("../Figures/compare_Pv3Rs_vs_prototype.png", 
             width = 7, height = 10, units = "in", res = 300)
par(mfcol = c(3,2), mar = par_default$mar)
for(s in states){
  
  plot(NULL, xlim = c(0,1), ylim = c(0,1), ylab = "Pv3Rs", xlab = "Prototype",
       bty = "n", main = paste0(names(which(states == s)), ": uniform prior"))
  abline(a = 0, b = 1, lty = "dotted")
  segments(y0 = Uniform_Pv3Rs[rownames(thetas_9MS_Tagnostic), s], 
           y1 = Uniform_Pv3Rs[rownames(thetas_9MS_Tagnostic), s], 
           x0 = thetas_9MS_Tagnostic[, paste0(s, "2.5%")], 
           x1 = thetas_9MS_Tagnostic[, paste0(s, "97.5%")], col = "darkgrey")
  points(x = thetas_9MS_Tagnostic[, paste0(s, "50%")], 
         y = Uniform_Pv3Rs[rownames(thetas_9MS_Tagnostic), s], 
         pch = 21, bg = "white", col = "darkgrey")
  # points(x = thetas_9MS_Tagnostic[, s], 
  #        y = Uniform_Pv3Rs[rownames(thetas_9MS_Tagnostic), s], 
  #        pch = 20, cex = 0.5)
  
  # Extract and annotate big differences: 3 diffs are NA 
  diffs <- abs(thetas_9MS_Tagnostic[, paste0(s, "50%")] - 
                 Uniform_Pv3Rs[rownames(thetas_9MS_Tagnostic), s])
  big_diffs_Uniform <- rownames(thetas_9MS_Tagnostic)[which(diffs > big_diff)]
  if(length(big_diffs_Uniform) > 0) {
    text(y = Uniform_Pv3Rs[big_diffs_Uniform, s], 
         x = thetas_9MS_Tagnostic[big_diffs_Uniform, paste0(s, "50%")], 
         cex = 0.75, labels = big_diffs_Uniform, 
         pos = if(s == "I") c(3,1,1,2,4,4,4) else c(1,3,3,4,2,2,2))  
  }
}
for(s in states){
  
  plot(NULL, xlim = c(0,1), ylim = c(0,1), ylab = "Pv3Rs", xlab = "Prototype", 
       bty = "n", main = paste0(names(which(states == s)), ": time-to-event prior"))
  abline(a = 0, b = 1, lty = "dotted")
  segments(y0 = TimeToEvent_Pv3Rs[rownames(MS_final), s], 
           y1 = TimeToEvent_Pv3Rs[rownames(MS_final), s], 
           x0 = MS_final[,sprintf("%s_lower", s)], 
           x1 = MS_final[,sprintf("%s_upper", s)], col = "darkgrey")
  points(x = MS_final[,sprintf("%s_median", s)], 
         y = TimeToEvent_Pv3Rs[rownames(MS_final), s], 
         pch = 21, bg = "white", col = "darkgrey")
  # points(x = thetas_9MS[, s], 
  #        y = TimeToEvent_Pv3Rs[rownames(thetas_9MS), s], 
  #        pch = 20, cex = 0.5)
  
  # Extract and annotate big differences 
  diffs <- abs(MS_final[,sprintf("%s_median", s)] 
               - TimeToEvent_Pv3Rs[rownames(MS_final), s])
  big_diffs_TimeToEvent <- rownames(MS_final)[which(diffs > big_diff)]
  if (length(big_diffs_TimeToEvent) > 0) {
    text(y = TimeToEvent_Pv3Rs[big_diffs_TimeToEvent, s], 
         x = MS_final[big_diffs_TimeToEvent, sprintf("%s_median", s)], 
         cex = 0.8, labels = big_diffs_TimeToEvent,
         pos = if(s == "I") c(4,3,3,1) else c(2,1,1,3)) # Choose pos by hand 
  }
} 



if(Figs) dev.off()

#===============================================================================
# Check counts joint (mean prototype available) versus pairwise or joint
#===============================================================================
length(rownames(MS_final))
length(rownames(thetas_9MS)[!is.na(thetas_9MS$`C50%`)]) 
length(rownames(thetas_9MS_Tagnostic)[!is.na(thetas_9MS_Tagnostic$`C50%`)]) 


#===============================================================================
# Results and data plots for discrepant estimates: In summary, 2 of 9 large
# deviations are undesirable, VHX_91_2 and VHX_56_2, both seems to be cases of
# half sibs
#===============================================================================
pids_big_diffs_TimeToEvent <- apply(do.call(rbind, strsplit(big_diffs_TimeToEvent, split = "_"))[,1:2], 
                                    1, paste, collapse = "_")
pids_big_diffs_Uniform <- apply(do.call(rbind, strsplit(big_diffs_Uniform, split = "_"))[,1:2], 
                                1, paste, collapse = "_")
intersect(big_diffs_TimeToEvent, big_diffs_Uniform) # Two are the same 
unique(c(big_diffs_TimeToEvent, big_diffs_Uniform)) # Nine unique 

#===============================================================================
# Visual inference for discrepant cases; summarised in ms figure below
#===============================================================================

# Plot data and inspect estimates for the participants with estimates that differ
plot_data(ys = ys_VHX_BPD[pids_big_diffs_TimeToEvent], fs = fs_VHX_BPD)
MS_final[big_diffs_TimeToEvent, c("C_median", "L_median", "I_median")] 
TimeToEvent_Pv3Rs[big_diffs_TimeToEvent,] 

# VHX_56_2: Pv3Rs closer to reinfection, seems to be a case of half-sib misspec. 
# BPD_253_3: Pv3Rs closer to reinfection, seems reasonable 
# VHX_419_6: Pv3Rs closer to reinfection, seems reasonable
# BPD_562_2: Pv3Rs closer to relapse, seems reasonable

# Plot data and inspect estimates for the participants with estimates that differ
plot_data(ys = ys_VHX_BPD[pids_big_diffs_Uniform], fs = fs_VHX_BPD)
thetas_9MS_Tagnostic[big_diffs_Uniform, c("C50%", "L50%", "I50%")] 
Uniform_Pv3Rs[big_diffs_Uniform,] 

# VHX_56_2: Pv3Rs closer to reinfection, seems to be a case of half-sib misspec. 
# BPD_253_3: Pv3Rs closer to reinfection, not unreasonable
# BPD_70_2: Pv3Rs closer to reinfection, not unreasonable
# VHX_214_2: Pv3Rs closer to reinfection, not unreasonable
# VHX_298_2: Pv3Rs closer to reinfection, not unreasonable
# VHD_452_2: Pv3Rs closer to reinfection, not unreasonable
# VHX_91_2: Pv3Rs closer to reinfection, seems to be a case of half-sib misspec. 


#===============================================================================
# MS quality figure 
#===============================================================================
pids <- unique(c(pids_big_diffs_Uniform, pids_big_diffs_TimeToEvent))
eids_both <- intersect(big_diffs_TimeToEvent, big_diffs_Uniform)

# Save for genetic proximity
eids_proto_pv3Rs <- c(TimeToEvent = big_diffs_TimeToEvent, Uniform = big_diffs_Uniform)
save(eids_proto_pv3Rs, file = "../RData/big_diffs_pv3rs_prototype.RData")

# Extract all episodes for pids with big difference
episodes <- unname(unlist(sapply(pids, function(pid) {
  sapply(names(ys_VHX_BPD[[pid]]), function(epi) {
    paste(pid, epi, sep = "_")})})))

# Extract probabilities for all recurrences in pids with at a discrepant recurrence
all_recs_pids_big_diff_Uniform <- unlist(sapply(pids_big_diffs_Uniform, function(pid) paste(pid, names(ys_VHX_BPD[[pid]])[-1], sep = "_")))
all_recs_pids_big_diff_TimeToEvent <- unlist(sapply(pids_big_diffs_TimeToEvent, function(pid) paste(pid, names(ys_VHX_BPD[[pid]])[-1], sep = "_")))

# Get relapse probability
L_Pv3Rs_Uniform <- Uniform_Pv3Rs[all_recs_pids_big_diff_Uniform, "L"]
L_Pv3Rs_TimeToEvent <- TimeToEvent_Pv3Rs[all_recs_pids_big_diff_TimeToEvent, "L"]
L_proto_Uniform <- thetas_9MS_Tagnostic[all_recs_pids_big_diff_Uniform, "L50%"]
L_proto_TimeToEvent <- MS_final[all_recs_pids_big_diff_TimeToEvent, "L_median"]
names(L_Pv3Rs_Uniform) <- names(L_proto_Uniform) <- all_recs_pids_big_diff_Uniform
names(L_Pv3Rs_TimeToEvent) <- names(L_proto_TimeToEvent) <- all_recs_pids_big_diff_TimeToEvent

no_episodes_per_pid <- sapply(ys_VHX_BPD[pids], length)
text_Pv3Rs <- text_proto <- rep("", length(episodes)) 
names(text_Pv3Rs) <- names(text_proto) <- episodes
text_Pv3Rs[all_recs_pids_big_diff_Uniform] <- round(L_Pv3Rs_Uniform, 2)*100 
text_Pv3Rs[all_recs_pids_big_diff_TimeToEvent] <- round(L_Pv3Rs_TimeToEvent, 2)*100 
text_proto[all_recs_pids_big_diff_Uniform] <- round(L_proto_Uniform, 2)*100
text_proto[all_recs_pids_big_diff_TimeToEvent] <- round(L_proto_TimeToEvent, 2)*100
text_Pv3Rs[eids_both] <- paste(round(L_Pv3Rs_Uniform[eids_both], 2)*100, 
                               round(L_Pv3Rs_TimeToEvent[eids_both], 2)*100, sep = "/")
text_proto[eids_both] <- paste(round(L_proto_Uniform[eids_both], 2)*100, 
                               round(L_proto_TimeToEvent[eids_both], 2)*100, sep = "/")
text_col <- unlist(sapply(1:length(pids), function(i){
  if(i %% 2 == 1) {
    rep("white", no_episodes_per_pid[i])
  } else {
    rep("black", no_episodes_per_pid[i])
  }}))
main_mar <- c(1.5, 3.5, 1.5, 3.5)
z <- 1/(2*length(episodes)) # See text x placement

# Plot for ms
if(Figs) png("../Figures/data_Pv3Rs_vs_prototype.png", width = 10, height = 7, units = "in", res = 300)
par(fig = c(0,1,0.2+0.01,1), mar = main_mar) # Important to call before and after plot_data
plot_data(ys = ys_VHX_BPD[pids], fs = fs_VHX_BPD, marker.annotate = F, mar = main_mar)
par(fig = c(0,1,0.2+0.01,1), mar = main_mar) # Important to call before and after plot_data
text(y = rep(0.01, length(episodes)),
     x = seq(z, 1-z, length.out = length(episodes)), 
     labels = text_Pv3Rs, cex = 0.5, col = text_col)
text(y = rep(0.04, length(episodes)),
     x = seq(z, 1-z, length.out = length(episodes)), 
     labels = text_proto, cex = 0.5, col = "black")
points(y = rep(-0.01, length(unique(c(big_diffs_TimeToEvent, big_diffs_Uniform)))),
       x = seq(z, 1-z, length.out = length(episodes))[episodes %in% unique(c(big_diffs_TimeToEvent, big_diffs_Uniform))], 
       pch = 17, cex = 0.6) 
if(Figs) dev.off()

# Checking BPD_562 uniform and prior:
load("../RData/prior_estimates.RData")
Uniform_Pv3Rs["BPD_562_2", "L"]
thetas_9MS_Tagnostic["BPD_562_2",]
prior["BPD_562_2",]

