################################################################################
# Old results include: 
#
# Those in thetas_9MS, which include mean (C, I, L) and quantiles (see above)
# for all data modelled jointly using the time-to-event prior
#
# Those in thetas_9MS_Tagnostic, which include  mean (C, I, L) and quantiles
# (see above) for all data modelled jointly using the uniform prior
#
# Those in MS_final, which is generated by running the code chunks in XXX. The
# results in MS_final include the 2.5, 0.5, 97.5 quantiles of the distributions
# generated by running the prototype 100 times, each time with a different draws
# from the time-to-event posterior and the posterior on allele frequencies. The
# results are generated using data modelled jointly or pairwise.
################################################################################

rm(list = ls())
library(Pv3Rs)
states <- c(Recrudescence = "C", Reinfection = "I", Relapse = "L")
par_default <- par()

load("../RData/marg_results_Pv3Rs.RData")
path <- "~/Documents/RecurrentVivax/" # Path to old estimates
load(sprintf('%sRData/GeneticModel/Including_Complex_Cases_Full_Posterior_Model_samples_Tagnostic.RData', path))
load(sprintf('%sRData/GeneticModel/Including_Complex_Cases_Full_Posterior_Model_samples.RData', path))
load("../Rdata/MS_final_generated_by_running_all_chunks_of_Pooled_Analysis.Rmd")
rownames(MS_final) <- MS_final[,"Episode_Identifier"]

# Check median values are the same across MS_final and thetas_9MS
all(MS_final[rownames(thetas_9MS), "C"] == thetas_9MS[,"C50%"], na.rm = T)
all(MS_final[rownames(thetas_9MS), "L"] == thetas_9MS[,"L50%"], na.rm = T)
all(MS_final[rownames(thetas_9MS), "I"] == thetas_9MS[,"I50%"], na.rm = T)
# thetas_9MS inc pids with total MOI 6 where MS_final doesnt, hence na.rm = T abv:
rownames(thetas_9MS)[!rownames(thetas_9MS) %in% rownames(MS_final)] 

#===============================================================================
# Plot on the simplex 
#===============================================================================
# Source function, project probabilities, add joint indicator, plot
source("plot_VHXBPD_simplex.R")
na_log <- !is.na(thetas_9MS_Tagnostic$`C50%`) # Some entries have NA estimates
Uniform_xy <- apply(thetas_9MS_Tagnostic[na_log, c("C50%", "L50%", "I50%")], 1, project2D)
TimeToEvent_xy <- apply(MS_final[,c("C_median", "L_median", "I_median")], 1, project2D)
Uniform_xy <- rbind(Uniform_xy, joint = 1) # uniform prior not run for pids 4+ episodes
TimeToEvent_xy <- rbind(TimeToEvent_xy, joint = colnames(TimeToEvent_xy) %in% rownames(thetas_9MS))
plot_VHXBPD_simplex(Uniform_xy, TimeToEvent_xy)

par(mfrow = c(2,3), mar = par_default$mar)


#===============================================================================
# Compare median and mean old: estimates based on jointly modelled data only
# Old notes transferred from Compare_recurrent_states: Small variation between mean and median using the uniform prior suggests
# variation due to time-to-event draws (which we can exactly reproduce)
# dominates variation due to posterior allele-frequency draws (which we cannot
# exactly reproduce). As such, generation of estimates for all 100 posterior
# time-to-event is not rendered worthless by the fact that we cannot recreate
# draws from the allele frequency posterior exactly (we didn't use set.seed in
# Pooled_Analysis.Rmd). Nonetheless, it is computationally expensive
#===============================================================================
for(s in states){
  plot(x = thetas_9MS[, paste0(s,"50%")], y = thetas_9MS[,s], 
       xlab = "Prototype median", ylab = "Prototype mean", 
       xlim = c(0,1), ylim = c(0,1), pch = 20, bty = "n", 
       main = sprintf("%s: time-to-event prior", names(which(states == s))))
  abline(a = 0, b = 1, lty = "dotted")}

for(s in states){  
  plot(x = thetas_9MS_Tagnostic[, paste0(s,"50%")], y = thetas_9MS_Tagnostic[,s], 
       xlab = "Prototype median", ylab = "Prototype mean", 
       xlim = c(0,1), ylim = c(0,1), pch = 20, bty = "n", 
       main = sprintf("%s: uniform prior", names(which(states == s))))
  abline(a = 0, b = 1, lty = "dotted")}


#===============================================================================
# Compare Pv3Rs and old Time-to-Event results:
# median for both jointly and pairwise modelled data 
# mean for jointly modelled data only
#===============================================================================

# Check overlap: 
all(rownames(MS_final) %in% rownames(TimeToEvent_Pv3Rs))
all(rownames(TimeToEvent_Pv3Rs) %in% rownames(MS_final))

# Check missing meets expectation: yes; see Analysable_data.png
rownames(TimeToEvent_Pv3Rs)[which(!rownames(TimeToEvent_Pv3Rs) %in% rownames(MS_final))]
# "VHX_239_2" "VHX_33_2"  "VHX_39_2"  "VHX_461_2" "VHX_52_2"  "VHX_583_2"

for(s in states){
  
  plot(NULL, xlim = c(0,1), ylim = c(0,1), ylab = "Pv3Rs", xlab = "Prototype", 
       bty = "n", main = paste0(names(which(states == s)), ": time-to-event prior")
  abline(a = 0, b = 1, lty = "dotted")
  segments(y0 = TimeToEvent_Pv3Rs[rownames(MS_final), s], 
           y1 = TimeToEvent_Pv3Rs[rownames(MS_final), s], 
           x0 = MS_final[,sprintf("%s_lower", s)], 
           x1 = MS_final[,sprintf("%s_upper", s)], col = "lightgrey")
  points(x = MS_final[,sprintf("%s_median", s)], 
         y = TimeToEvent_Pv3Rs[rownames(MS_final), s], 
         pch = 21, bg = "white", col = "lightgrey")
  points(x = thetas_9MS[, s], 
         y = TimeToEvent_Pv3Rs[rownames(thetas_9MS), s], 
         pch = 20, cex = 0.5)
  
  # Extract and annotate big differences 
  diffs <- abs(MS_final[,sprintf("%s_median", s)] 
               - TimeToEvent_Pv3Rs[rownames(MS_final), s])
  big_diffs <- rownames(MS_final)[which(diffs > 0.25)]
  if (length(big_diffs) > 0) {
    text(y = TimeToEvent_Pv3Rs[big_diffs, s], 
         x = MS_final[big_diffs, sprintf("%s_median", s)], 
         cex = 0.8, labels = big_diffs,
         pos = if(s == "I") c(4,1,1,1) else c(2,1,1,3)) # Choose pos by hand 
  }
} 

#===============================================================================
# Compare Uniform results:
# median and mean for joint only
#===============================================================================

for(s in states){
  
  plot(NULL, xlim = c(0,1), ylim = c(0,1), ylab = "Pv3Rs", xlab = "Prototype",
       bty = "n", main = paste0(names(which(states == s)), ": uniform prior"))
  abline(a = 0, b = 1, lty = "dotted")
  segments(y0 = Uniform_Pv3Rs[rownames(thetas_9MS_Tagnostic), s], 
           y1 = Uniform_Pv3Rs[rownames(thetas_9MS_Tagnostic), s], 
           x0 = thetas_9MS_Tagnostic[, paste0(s, "2.5%")], 
           x1 = thetas_9MS_Tagnostic[, paste0(s, "97.5%")], col = "lightgrey")
  points(x = thetas_9MS_Tagnostic[, paste0(s, "50%")], 
         y = Uniform_Pv3Rs[rownames(thetas_9MS_Tagnostic), s], 
         pch = 21, bg = "white", col = "lightgrey")
  points(x = thetas_9MS_Tagnostic[, s], 
         y = Uniform_Pv3Rs[rownames(thetas_9MS_Tagnostic), s], 
         pch = 20, cex = 0.5)
  
  # Extract and annotate big differences 
  diffs <- abs(thetas_9MS_Tagnostic[, paste0(s, "50%")] - 
                 Uniform_Pv3Rs[rownames(thetas_9MS_Tagnostic), s])
  big_diffs <- rownames(thetas_9MS_Tagnostic)[which(diffs > 0.25)]
  if(length(big_diffs) > 0) {
    text(y = Uniform_Pv3Rs[big_diffs, s], 
         x = thetas_9MS_Tagnostic[big_diffs, paste0(s, "50%")], 
         cex = 0.75, labels = big_diffs, 
         pos = if(s == "L") c(1,3,3,1,2,2,2) else c(3,1,1,3,4,4,4))  
  }
}


#===============================================================================
# Data plots: extract pids of big diffs by hand 
# Old notes transferred from Compare_recurrent_states: 2 of 8 large deviations are undesirable: VHX_91_2 and VHX_56_2 
# Another good example: VHX_91_3, but not as impacted because VHX_91_3 is not polyclonal
# Write a vignette around VHX_91_2 and VHX_91_3 and VHX_56_2, 
# VHX_91 seems to be a true half-sib. VHX_56_2 illustrates problem of new model relapse 
# being more brittle to genotyping errors where it was not before
#===============================================================================
big_diffs_TimeToEvent <- c("VHX_56", "VHX_419", "BPD_562", "BPD_253")
big_diffs_Uniform <- c("BPD_253", "BPD_70", "VHX_214", "VHX_298", "VHX_452", "VHX_56", "VHX_91")

# Plot data and inspect estimates for the participants with estimates that differ
# Both 5/9 match; rarer alleles for BPD_562...
plot_data(ys = ys_VHX_BPD[big_diffs_TimeToEvent], fs = fs_VHX_BPD)
MS_final[big_diffs, c("C_median", "L_median", "I_median")] 
TimeToEvent_Pv3Rs[big_diffs,] # BPD more reasonable; VHX: half sib missclassification 

# Plot data and inspect estimates for the participants with estimates that differ
# Both 5/9 match; rarer alleles for BPD_562...
plot_data(ys = ys_VHX_BPD[big_diffs_Uniform], fs = fs_VHX_BPD)
thetas_9MS_Tagnostic[big_diffs, c("C50%", "L50%", "I50%")] 
Uniform_Pv3Rs[big_diffs,] # BPD more reasonable; VHX: half sib missclassification 

