################################################################################
# Old results include: 
#
# Those in thetas_9MS, which include mean (C, I, L) and quantiles (see above)
# for all data modelled jointly using the time-to-event prior
#
# Those in thetas_9MS_Tagnostic, which include  mean (C, I, L) and quantiles
# (see above) for all data modelled jointly using the uniform prior
#
# Those in MS_final, which is generated by running the code chunks in XXX. The
# results in MS_final include the 2.5, 0.5, 97.5 quantiles of the distributions
# generated by running the prototype 100 times, each time with a different draws
# from the time-to-event posterior and the posterior on allele frequencies. The
# results are generated using data modelled jointly or pairwise.
################################################################################

rm(list = ls())


path <- "~/Documents/RecurrentVivax/" # Path to old estimates
load(sprintf('%sRData/GeneticModel/Including_Complex_Cases_Full_Posterior_Model_samples_Tagnostic.RData', path))
load(sprintf('%sRData/GeneticModel/Including_Complex_Cases_Full_Posterior_Model_samples.RData', path))
load("../Rdata/MS_final_generated_by_running_all_chunks_of_Pooled_Analysis.Rmd")

# Create a matrix of estimates using MS_final
TimeToEvent_old <- data.frame(C = MS_final[,"C_median"], L = MS_final[,"L_median"], I = MS_final[,"I_median"])
rownames(TimeToEvent_old) <- MS_final[,"Episode_Identifier"]
TimeToEvent_old$joint <- MS_final[,"TotalEpisodes"] <= 3

# Check the median estimates from MS_final agree with those in thetas_9MS
all(TimeToEvent_old[rownames(thetas_9MS), "C"] == thetas_9MS[,"C50%"], na.rm = T)
all(TimeToEvent_old[rownames(thetas_9MS), "L"] == thetas_9MS[,"L50%"], na.rm = T)
all(TimeToEvent_old[rownames(thetas_9MS), "I"] == thetas_9MS[,"I50%"], na.rm = T)
# thetas_9MS inc pids with total MOI 6 where MS_final doesnt, hence na.rm = T abv:
rownames(thetas_9MS)[!rownames(thetas_9MS) %in% rownames(TimeToEvent_old)] 


#===============================================================================
# Compare Time-to-Event results
#===============================================================================
load("../RData/marg_results_Pv3Rs.RData")

# Check overlap 
all(rownames(TimeToEvent_old) %in% rownames(TimeToEvent_Pv3Rs))
all(rownames(TimeToEvent_Pv3Rs) %in% rownames(TimeToEvent_old))

# Check missing meets expectation: yes; see Analysable_data.png
rownames(TimeToEvent_Pv3Rs)[which(!rownames(TimeToEvent_Pv3Rs) %in% rownames(TimeToEvent_old))]
# "VHX_239_2" "VHX_33_2"  "VHX_39_2"  "VHX_461_2" "VHX_52_2"  "VHX_583_2"

# Compare old and new relapse probabilities
par(mfrow = c(2,2))
plot(y = TimeToEvent_old[,"I"], 
     x = TimeToEvent_Pv3Rs[rownames(TimeToEvent_old), "I"],
     pch = 20, col = 1+grepl("BPD", rownames(TimeToEvent_old)))
abline(a = 0, b = 1, lty = "dotted")
plot(y = TimeToEvent_old[,"C"], 
     x = TimeToEvent_Pv3Rs[rownames(TimeToEvent_old), "C"],
     pch = 20, col = 1+grepl("BPD", rownames(TimeToEvent_old)))
abline(a = 0, b = 1, lty = "dotted")

plot(y = TimeToEvent_old[,"L"], 
     x = TimeToEvent_Pv3Rs[rownames(TimeToEvent_old), "L"],
     pch = 20, col = 1+grepl("BPD", rownames(TimeToEvent_old)))
abline(a = 0, b = 1, lty = "dotted")
# Extract and annotate big differences 
diffs <- abs(TimeToEvent_old[,"L"] - TimeToEvent_Pv3Rs[rownames(TimeToEvent_old), "L"])
big_diffs <- rownames(TimeToEvent_old)[which(diffs > 0.4)]
text(x = TimeToEvent_Pv3Rs[big_diffs, "L"], y = TimeToEvent_old[big_diffs, "L"], 
     labels = big_diffs, pos = c(4,2))

# Plot data and inspect estimates for the participants with estimates that differ
# Both 5/9 match; rarer alleles for BPD_562...
plot_data(ys = ys_VHX_BPD[c("VHX_56", "BPD_562")], fs = fs_VHX_BPD)
TimeToEvent_old[big_diffs,] 
TimeToEvent_Pv3Rs[big_diffs,] # BPD more reasonable; VHX: half sib missclassification 

