################################################################################
# There are three issues around
# estimation in Taylor&Watson: caption of Table 1 of Taylor&Watson "Five
# patients had unpaired thus unanalyzable genetic data. Data from six paired
# recurrences were omitted due to computational complexity", plus the pairwise
# hack, which was done for all pids with four or more episodes.
#
# 1) Estimation impossible: data on only one episode
# 2) Estimation impossible: cumulative MOI of 6 or more across 2 first episodes
# 3) Estimation slow: UpperComplexityIDs, which contains some impossible
# 
# In this script I use MS_final generated by running Pool_Analysus.Rmd. I think
# RecurrentVivax/RData/FinalRecurrenceEstimates.RData is deprecated: it contains
# mean recurrent estimates whereas MS_final generated by Pool_Analysis.Rmd does
# not (failure rates computed in Pool_Analysis and thus the publication are
# based on medians). Summary_data_ModelResults.RData is up-to-date, but only the
# per-patient estimates are reliable (Summary_data$Reinfection_Probability, for
# example, is just left over from line 1985). Results for recurrences where data
# were modelled jointly are in:
#
#~/Documents/RecurrentVivax/RData/GeneticModel/Including_Complex_Cases_Full_Posterior_Model_samples_Tagnostic.RData
#~/Documents/RecurrentVivax/RData/GeneticModel/Including_Complex_Cases_Full_Posterior_Model_samples.RData
################################################################################

# Set up
load("../../RData/MS_final_generated_by_running_all_chunks_of_Pooled_Analysis.Rmd")
any(is.na(MS_final$L_median)) # MS_final doesn't contain any entries with NA estimates

# Reload genetic data for plotting since Pool_Analysis.Rmd adds columns
load("~/Documents/RecurrentVivax/RData/GeneticModel/MS_data_PooledAnalysis.RData")

# Generate a table of MOIs: sufficient statistic for feasibility of estimation
max_epi_count <- max(MS_pooled$Episode) # Possibly overlooks episodes without genetic data
y.dfs <- plyr::dlply(MS_pooled, 'ID') # Split data by participant
tab_MOIs <- t(sapply(y.dfs, function(y.df) { 
  z <- rep(NA, max_epi_count + 1) # Generate a MOI vector template with NAs for non-episodes
  names(z) <- c(1:max_epi_count, "total") # Name s.t. MOIs can be entered by episode
  x <- sapply(plyr::dlply(y.df, 'Episode'), nrow) # Extract per-participant MOI vector
  z[names(x)] <- x # Enter MOIs by episode
  z["total"] <- sum(x) # Enter total genotype count
  return(z)}))

# ==============================================================================
# IDs in MS_pooled but not MS_final: 
# only enrolment data (4 IDs), 
# unpaired recurrent data (1 ID), 
# data with 6 or more genotypes in < 3 episodes (4 IDs)
# ==============================================================================
missingIDs <- unique(MS_pooled$ID[!MS_pooled$ID %in% MS_final$ID])
tab_MOIs[missingIDs,]

# ==============================================================================
# Computational complexity: 
# Of 493 recurrences analysed (recurrences with paired data), 6 (see
# missing_from_MS_final in Pooled_Analysis.Rmd and missingRecIDs) were too
# complex to estimate recurrence state probabilities: "VHX_239_2" "VHX_33_2"
# "VHX_39_2"  "VHX_461_2" "VHX_52_2"  "VHX_583_2", resulting in probability
# estimates for a total of 487 recurrences from 208 individuals (77 BPD and 131
# VHX); "VHX_33", "VHX_583" not in missingIDs because some of their recurrences
# were analysable.
# ==============================================================================
log_missingEpiIDs <- !MS_pooled$Episode_Identifier %in% MS_final$Episode_Identifier
log_rec <- MS_pooled$Episode > 1
missingRecIDs <- unique(MS_pooled$Episode_Identifier[log_missingEpiIDs & log_rec])
missingRecIDs # Includes all missingIDs with recurrent data plus VHX33 and VHX583
tab_MOIs[c("VHX_33", "VHX_583"),] # First-second pairwise analysis exceeds 6 genotypes

# ==============================================================================
# UpperComplexityIDs: slow execution
# ==============================================================================
# There are 9 patients with complex data that considerably increase computation
# time. To aid illustrative runs of the code, these were not analysed when
# EXCLUDE_COMPLEX = T. They are:
#
# "VHX_239" "VHX_461" "VHX_52"  # These have MOIs of 6 
# "VHX_16"  "VHX_225" "VHX_33"  
# "VHX_551" "VHX_583" "VHX_646"
# 
# When EXCLUDE_COMPLEX = F, NAs are returned for data on VHX_239 VHX_461 and
# VHX_52; estimates are computed for "VHX_16"  "VHX_225" "VHX_33" "VHX_551"
# "VHX_583" "VHX_646"
load('../RData/UpperComplexityIDs.RData')
UpperComplexityIDs[UpperComplexityIDs %in% MS_final$ID] # 6 of the UpperComplexityIDs
tab_MOIs[UpperComplexityIDs[UpperComplexityIDs %in% MS_final$ID],]

# ==============================================================================
# post_prob_CLI.R states the following; participants with sum(MOIs) = 6 don't
# have estimates likely due to UpperComplexity. 
# Max_Eps = 3 (one or two recurrence)
# Max_Tot_Vtx = 6 (total of six of fewer genotypes)

# For samples with more than three episodes, estimates were generated using a
# pairwise hac referred to as inflated. The following is a quote from Taylor &
# Watson et al. 2019. Please note, I don't understand what was meant by taking a
# complement and then re-weight and I can't find the relevant in the code. I'm
# assuming we actually meant take a complement if P(L)+P(C) <= 1; otherwise, re-weight.

# From the ms: "The computational complexity of the genetic model limits it to
# the joint analysis of three episodes (two recurrences) per patient (in our
# data this is the case for 158 patients). For each individual with more than
# two recurrences (54 patients), we estimated pairwise probabilities of
# recurrence states between episodes (using the above model) and constructed an
# adjacency matrix. Relapse probabilities were then defined as proportional to
# the maximum estimated probability of relapse with respect to all preceding
# episodes, and those of recrudescence with respect to the directly preceding
# episode. The probability of reinfection is the complement of the probability
# of relapse plus recrudescence. These probabilities were then re-weighted to
# sum to 1."
# ==============================================================================







